name: Electron Build and Publish (Windows)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.19.0"

      - name: Install dependencies
        run: npm install -f
    
      - name: Build and Publish
        run: CI=false npm run publish:mac

