name: Electron Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: macos-latest
            node_js: "16"
          - os: windows-latest
            node_js: "16"

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_js }}

      - name: Install dependencies
        run: |
          yarn --frozen-lockfile

      - name: Build Electron app
        run: |
          if [ "$RUN_ON" == "macos" ]; then
            yarn release --mac
          elif [ "$RUN_ON" == "windows" ]; then
            yarn release --win
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: true
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path/to/your/release/assets
          asset_name: your-asset-name.ext
          asset_content_type: application/octet-stream
